import sys
import json
import os


def update_hyprland_hdr_options(jsonData):
    hdr_conf_path = f"{os.path.expanduser('~')}/.config/hypr/hdr.conf"

    configContent = ""
    for monitor in jsonData:
        name = monitor.get("name")
        cm = "hdr" if monitor.get("hdrEnabled") else "srgb"
        configContent += f"monitorv2 {{\n  output = {name}\n  cm = {cm}\n}}\n"

    try:
        os.makedirs(os.path.dirname(hdr_conf_path), exist_ok=True)
        with open(hdr_conf_path, "w") as f:
            f.write(
                f"# The values below are autogenerated. Do not change them manually.\n"
                f"{configContent}"
            )

        print("Hyprland HDR configuration updated successfully.")
    except Exception as e:
        print(f"Error while updating hyprland configuration: {e}")
        return


def main():
    if len(sys.argv) != 2:
        print("Usage: python toggle-hdr.py <options>")
        sys.exit(1)

    try:
        info_json = json.loads(sys.argv[1])
        update_hyprland_hdr_options(info_json)
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON given {sys.argv[1]}")
        sys.exit(1)


if __name__ == "__main__":
    main()
