# Here you can put your custom Hyprland overrides

# Autostart applications
# exec-once = [workspace 1 silent] kitty

# HDR required variables
# env = DXVK_HDR,1
# env = ENABLE_HDR_WSI,1

# Custom keyboard layout
# input:kb_layout = pl

# Additional env for nvidia users
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
